// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/admin/catalog_admin_service.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogAdminService_CreateCategory_FullMethodName         = "/martketplace.vkr.catalog.v1.admin.CatalogAdminService/CreateCategory"
	CatalogAdminService_UpdateCategory_FullMethodName         = "/martketplace.vkr.catalog.v1.admin.CatalogAdminService/UpdateCategory"
	CatalogAdminService_DeleteCategory_FullMethodName         = "/martketplace.vkr.catalog.v1.admin.CatalogAdminService/DeleteCategory"
	CatalogAdminService_GetUSDTExchangeRate_FullMethodName    = "/martketplace.vkr.catalog.v1.admin.CatalogAdminService/GetUSDTExchangeRate"
	CatalogAdminService_UpdateUSDTExchangeRate_FullMethodName = "/martketplace.vkr.catalog.v1.admin.CatalogAdminService/UpdateUSDTExchangeRate"
)

// CatalogAdminServiceClient is the client API for CatalogAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogAdminServiceClient interface {
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	GetUSDTExchangeRate(ctx context.Context, in *GetUSDTExchangeRateRequest, opts ...grpc.CallOption) (*GetUSDTExchangeRateResponse, error)
	UpdateUSDTExchangeRate(ctx context.Context, in *UpdateUSDTExchangeRateRequest, opts ...grpc.CallOption) (*UpdateUSDTExchangeRateResponse, error)
}

type catalogAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogAdminServiceClient(cc grpc.ClientConnInterface) CatalogAdminServiceClient {
	return &catalogAdminServiceClient{cc}
}

func (c *catalogAdminServiceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, CatalogAdminService_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogAdminServiceClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, CatalogAdminService_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogAdminServiceClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, CatalogAdminService_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogAdminServiceClient) GetUSDTExchangeRate(ctx context.Context, in *GetUSDTExchangeRateRequest, opts ...grpc.CallOption) (*GetUSDTExchangeRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUSDTExchangeRateResponse)
	err := c.cc.Invoke(ctx, CatalogAdminService_GetUSDTExchangeRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogAdminServiceClient) UpdateUSDTExchangeRate(ctx context.Context, in *UpdateUSDTExchangeRateRequest, opts ...grpc.CallOption) (*UpdateUSDTExchangeRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUSDTExchangeRateResponse)
	err := c.cc.Invoke(ctx, CatalogAdminService_UpdateUSDTExchangeRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogAdminServiceServer is the server API for CatalogAdminService service.
// All implementations must embed UnimplementedCatalogAdminServiceServer
// for forward compatibility.
type CatalogAdminServiceServer interface {
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	GetUSDTExchangeRate(context.Context, *GetUSDTExchangeRateRequest) (*GetUSDTExchangeRateResponse, error)
	UpdateUSDTExchangeRate(context.Context, *UpdateUSDTExchangeRateRequest) (*UpdateUSDTExchangeRateResponse, error)
	mustEmbedUnimplementedCatalogAdminServiceServer()
}

// UnimplementedCatalogAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogAdminServiceServer struct{}

func (UnimplementedCatalogAdminServiceServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedCatalogAdminServiceServer) UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedCatalogAdminServiceServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedCatalogAdminServiceServer) GetUSDTExchangeRate(context.Context, *GetUSDTExchangeRateRequest) (*GetUSDTExchangeRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUSDTExchangeRate not implemented")
}
func (UnimplementedCatalogAdminServiceServer) UpdateUSDTExchangeRate(context.Context, *UpdateUSDTExchangeRateRequest) (*UpdateUSDTExchangeRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUSDTExchangeRate not implemented")
}
func (UnimplementedCatalogAdminServiceServer) mustEmbedUnimplementedCatalogAdminServiceServer() {}
func (UnimplementedCatalogAdminServiceServer) testEmbeddedByValue()                             {}

// UnsafeCatalogAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogAdminServiceServer will
// result in compilation errors.
type UnsafeCatalogAdminServiceServer interface {
	mustEmbedUnimplementedCatalogAdminServiceServer()
}

func RegisterCatalogAdminServiceServer(s grpc.ServiceRegistrar, srv CatalogAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatalogAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogAdminService_ServiceDesc, srv)
}

func _CatalogAdminService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogAdminServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogAdminService_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogAdminServiceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogAdminService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogAdminServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogAdminService_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogAdminServiceServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogAdminService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogAdminServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogAdminService_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogAdminServiceServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogAdminService_GetUSDTExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUSDTExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogAdminServiceServer).GetUSDTExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogAdminService_GetUSDTExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogAdminServiceServer).GetUSDTExchangeRate(ctx, req.(*GetUSDTExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogAdminService_UpdateUSDTExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUSDTExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogAdminServiceServer).UpdateUSDTExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogAdminService_UpdateUSDTExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogAdminServiceServer).UpdateUSDTExchangeRate(ctx, req.(*UpdateUSDTExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogAdminService_ServiceDesc is the grpc.ServiceDesc for CatalogAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "martketplace.vkr.catalog.v1.admin.CatalogAdminService",
	HandlerType: (*CatalogAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategory",
			Handler:    _CatalogAdminService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _CatalogAdminService_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _CatalogAdminService_DeleteCategory_Handler,
		},
		{
			MethodName: "GetUSDTExchangeRate",
			Handler:    _CatalogAdminService_GetUSDTExchangeRate_Handler,
		},
		{
			MethodName: "UpdateUSDTExchangeRate",
			Handler:    _CatalogAdminService_UpdateUSDTExchangeRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/admin/catalog_admin_service.proto",
}
