// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/admin/catalog_admin_service.proto

package admin

import (
	domain "github.com/martketplace-vkr/catalog/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      *int64                 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_catalog_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *domain.Category       `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_catalog_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCategoryResponse) GetCategory() *domain.Category {
	if x != nil {
		return x.Category
	}
	return nil
}

// Update replaces all mutable category fields.
// Omit parent_id to make the category a root category.
type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      *int64                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_catalog_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *domain.Category       `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_catalog_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCategoryResponse) GetCategory() *domain.Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_catalog_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_catalog_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_catalog_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCategoryResponse) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

var File_v1_admin_catalog_admin_service_proto protoreflect.FileDescriptor

const file_v1_admin_catalog_admin_service_proto_rawDesc = "" +
	"\n" +
	"$v1/admin/catalog_admin_service.proto\x12!martketplace.vkr.catalog.v1.admin\x1a\x1ev1/domain/catalog_domain.proto\"[\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\tparent_id\x18\x02 \x01(\x03H\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"b\n" +
	"\x16CreateCategoryResponse\x12H\n" +
	"\bcategory\x18\x01 \x01(\v2,.martketplace.vkr.catalog.v1.domain.CategoryR\bcategory\"|\n" +
	"\x15UpdateCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x03H\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"b\n" +
	"\x16UpdateCategoryResponse\x12H\n" +
	"\bcategory\x18\x01 \x01(\v2,.martketplace.vkr.catalog.v1.domain.CategoryR\bcategory\"8\n" +
	"\x15DeleteCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\"9\n" +
	"\x16DeleteCategoryResponse\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId2\xad\x03\n" +
	"\x13CatalogAdminService\x12\x85\x01\n" +
	"\x0eCreateCategory\x128.martketplace.vkr.catalog.v1.admin.CreateCategoryRequest\x1a9.martketplace.vkr.catalog.v1.admin.CreateCategoryResponse\x12\x85\x01\n" +
	"\x0eUpdateCategory\x128.martketplace.vkr.catalog.v1.admin.UpdateCategoryRequest\x1a9.martketplace.vkr.catalog.v1.admin.UpdateCategoryResponse\x12\x85\x01\n" +
	"\x0eDeleteCategory\x128.martketplace.vkr.catalog.v1.admin.DeleteCategoryRequest\x1a9.martketplace.vkr.catalog.v1.admin.DeleteCategoryResponseBAZ?github.com/martketplace-vkr/catalog/pkg/api/grpc/v1/admin;adminb\x06proto3"

var (
	file_v1_admin_catalog_admin_service_proto_rawDescOnce sync.Once
	file_v1_admin_catalog_admin_service_proto_rawDescData []byte
)

func file_v1_admin_catalog_admin_service_proto_rawDescGZIP() []byte {
	file_v1_admin_catalog_admin_service_proto_rawDescOnce.Do(func() {
		file_v1_admin_catalog_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_catalog_admin_service_proto_rawDesc), len(file_v1_admin_catalog_admin_service_proto_rawDesc)))
	})
	return file_v1_admin_catalog_admin_service_proto_rawDescData
}

var file_v1_admin_catalog_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_admin_catalog_admin_service_proto_goTypes = []any{
	(*CreateCategoryRequest)(nil),  // 0: martketplace.vkr.catalog.v1.admin.CreateCategoryRequest
	(*CreateCategoryResponse)(nil), // 1: martketplace.vkr.catalog.v1.admin.CreateCategoryResponse
	(*UpdateCategoryRequest)(nil),  // 2: martketplace.vkr.catalog.v1.admin.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil), // 3: martketplace.vkr.catalog.v1.admin.UpdateCategoryResponse
	(*DeleteCategoryRequest)(nil),  // 4: martketplace.vkr.catalog.v1.admin.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil), // 5: martketplace.vkr.catalog.v1.admin.DeleteCategoryResponse
	(*domain.Category)(nil),        // 6: martketplace.vkr.catalog.v1.domain.Category
}
var file_v1_admin_catalog_admin_service_proto_depIdxs = []int32{
	6, // 0: martketplace.vkr.catalog.v1.admin.CreateCategoryResponse.category:type_name -> martketplace.vkr.catalog.v1.domain.Category
	6, // 1: martketplace.vkr.catalog.v1.admin.UpdateCategoryResponse.category:type_name -> martketplace.vkr.catalog.v1.domain.Category
	0, // 2: martketplace.vkr.catalog.v1.admin.CatalogAdminService.CreateCategory:input_type -> martketplace.vkr.catalog.v1.admin.CreateCategoryRequest
	2, // 3: martketplace.vkr.catalog.v1.admin.CatalogAdminService.UpdateCategory:input_type -> martketplace.vkr.catalog.v1.admin.UpdateCategoryRequest
	4, // 4: martketplace.vkr.catalog.v1.admin.CatalogAdminService.DeleteCategory:input_type -> martketplace.vkr.catalog.v1.admin.DeleteCategoryRequest
	1, // 5: martketplace.vkr.catalog.v1.admin.CatalogAdminService.CreateCategory:output_type -> martketplace.vkr.catalog.v1.admin.CreateCategoryResponse
	3, // 6: martketplace.vkr.catalog.v1.admin.CatalogAdminService.UpdateCategory:output_type -> martketplace.vkr.catalog.v1.admin.UpdateCategoryResponse
	5, // 7: martketplace.vkr.catalog.v1.admin.CatalogAdminService.DeleteCategory:output_type -> martketplace.vkr.catalog.v1.admin.DeleteCategoryResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_admin_catalog_admin_service_proto_init() }
func file_v1_admin_catalog_admin_service_proto_init() {
	if File_v1_admin_catalog_admin_service_proto != nil {
		return
	}
	file_v1_admin_catalog_admin_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_admin_catalog_admin_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_catalog_admin_service_proto_rawDesc), len(file_v1_admin_catalog_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_catalog_admin_service_proto_goTypes,
		DependencyIndexes: file_v1_admin_catalog_admin_service_proto_depIdxs,
		MessageInfos:      file_v1_admin_catalog_admin_service_proto_msgTypes,
	}.Build()
	File_v1_admin_catalog_admin_service_proto = out.File
	file_v1_admin_catalog_admin_service_proto_goTypes = nil
	file_v1_admin_catalog_admin_service_proto_depIdxs = nil
}
