// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/domain/catalog_domain.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Children      []*Category            `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_v1_domain_catalog_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Category) GetChildren() []*Category {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Product struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Id                 int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendorId           int64                    `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	CategoryId         int64                    `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name               string                   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price              string                   `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	StockCount         uint32                   `protobuf:"varint,7,opt,name=stock_count,json=stockCount,proto3" json:"stock_count,omitempty"`
	Attributes         []*ProductAttribute      `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Images             []*ProductImage          `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt          *timestamppb.Timestamp   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Characteristics    []*ProductCharacteristic `protobuf:"bytes,12,rep,name=characteristics,proto3" json:"characteristics,omitempty"`
	AcceptsCrypto      bool                     `protobuf:"varint,13,opt,name=accepts_crypto,json=acceptsCrypto,proto3" json:"accepts_crypto,omitempty"`
	CryptoPricingMode  string                   `protobuf:"bytes,14,opt,name=crypto_pricing_mode,json=cryptoPricingMode,proto3" json:"crypto_pricing_mode,omitempty"`
	CryptoPriceUsdt    string                   `protobuf:"bytes,15,opt,name=crypto_price_usdt,json=cryptoPriceUsdt,proto3" json:"crypto_price_usdt,omitempty"`
	EffectiveUsdtPrice string                   `protobuf:"bytes,16,opt,name=effective_usdt_price,json=effectiveUsdtPrice,proto3" json:"effective_usdt_price,omitempty"`
	RubPerUsdt         string                   `protobuf:"bytes,17,opt,name=rub_per_usdt,json=rubPerUsdt,proto3" json:"rub_per_usdt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_v1_domain_catalog_domain_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *Product) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Product) GetStockCount() uint32 {
	if x != nil {
		return x.StockCount
	}
	return 0
}

func (x *Product) GetAttributes() []*ProductAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Product) GetImages() []*ProductImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetCharacteristics() []*ProductCharacteristic {
	if x != nil {
		return x.Characteristics
	}
	return nil
}

func (x *Product) GetAcceptsCrypto() bool {
	if x != nil {
		return x.AcceptsCrypto
	}
	return false
}

func (x *Product) GetCryptoPricingMode() string {
	if x != nil {
		return x.CryptoPricingMode
	}
	return ""
}

func (x *Product) GetCryptoPriceUsdt() string {
	if x != nil {
		return x.CryptoPriceUsdt
	}
	return ""
}

func (x *Product) GetEffectiveUsdtPrice() string {
	if x != nil {
		return x.EffectiveUsdtPrice
	}
	return ""
}

func (x *Product) GetRubPerUsdt() string {
	if x != nil {
		return x.RubPerUsdt
	}
	return ""
}

type ProductAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttribute) Reset() {
	*x = ProductAttribute{}
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttribute) ProtoMessage() {}

func (x *ProductAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttribute.ProtoReflect.Descriptor instead.
func (*ProductAttribute) Descriptor() ([]byte, []int) {
	return file_v1_domain_catalog_domain_proto_rawDescGZIP(), []int{2}
}

func (x *ProductAttribute) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProductAttributeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttributeInput) Reset() {
	*x = ProductAttributeInput{}
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttributeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeInput) ProtoMessage() {}

func (x *ProductAttributeInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeInput.ProtoReflect.Descriptor instead.
func (*ProductAttributeInput) Descriptor() ([]byte, []int) {
	return file_v1_domain_catalog_domain_proto_rawDescGZIP(), []int{3}
}

func (x *ProductAttributeInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAttributeInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProductCharacteristic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Attributes    []*ProductAttribute    `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCharacteristic) Reset() {
	*x = ProductCharacteristic{}
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCharacteristic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCharacteristic) ProtoMessage() {}

func (x *ProductCharacteristic) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCharacteristic.ProtoReflect.Descriptor instead.
func (*ProductCharacteristic) Descriptor() ([]byte, []int) {
	return file_v1_domain_catalog_domain_proto_rawDescGZIP(), []int{4}
}

func (x *ProductCharacteristic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductCharacteristic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductCharacteristic) GetAttributes() []*ProductAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ProductCharacteristicInput struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Title         string                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Attributes    []*ProductAttributeInput `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCharacteristicInput) Reset() {
	*x = ProductCharacteristicInput{}
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCharacteristicInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCharacteristicInput) ProtoMessage() {}

func (x *ProductCharacteristicInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCharacteristicInput.ProtoReflect.Descriptor instead.
func (*ProductCharacteristicInput) Descriptor() ([]byte, []int) {
	return file_v1_domain_catalog_domain_proto_rawDescGZIP(), []int{5}
}

func (x *ProductCharacteristicInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductCharacteristicInput) GetAttributes() []*ProductAttributeInput {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ProductImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	IsMain        bool                   `protobuf:"varint,3,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImage) Reset() {
	*x = ProductImage{}
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImage) ProtoMessage() {}

func (x *ProductImage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImage.ProtoReflect.Descriptor instead.
func (*ProductImage) Descriptor() ([]byte, []int) {
	return file_v1_domain_catalog_domain_proto_rawDescGZIP(), []int{6}
}

func (x *ProductImage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductImage) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

type ProductImageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	IsMain        bool                   `protobuf:"varint,2,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImageInput) Reset() {
	*x = ProductImageInput{}
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImageInput) ProtoMessage() {}

func (x *ProductImageInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_catalog_domain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImageInput.ProtoReflect.Descriptor instead.
func (*ProductImageInput) Descriptor() ([]byte, []int) {
	return file_v1_domain_catalog_domain_proto_rawDescGZIP(), []int{7}
}

func (x *ProductImageInput) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductImageInput) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

var File_v1_domain_catalog_domain_proto protoreflect.FileDescriptor

const file_v1_domain_catalog_domain_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/domain/catalog_domain.proto\x12\"martketplace.vkr.catalog.v1.domain\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12H\n" +
	"\bchildren\x18\x04 \x03(\v2,.martketplace.vkr.catalog.v1.domain.CategoryR\bchildren\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x96\x06\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1f\n" +
	"\vstock_count\x18\a \x01(\rR\n" +
	"stockCount\x12T\n" +
	"\n" +
	"attributes\x18\b \x03(\v24.martketplace.vkr.catalog.v1.domain.ProductAttributeR\n" +
	"attributes\x12H\n" +
	"\x06images\x18\t \x03(\v20.martketplace.vkr.catalog.v1.domain.ProductImageR\x06images\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12c\n" +
	"\x0fcharacteristics\x18\f \x03(\v29.martketplace.vkr.catalog.v1.domain.ProductCharacteristicR\x0fcharacteristics\x12%\n" +
	"\x0eaccepts_crypto\x18\r \x01(\bR\racceptsCrypto\x12.\n" +
	"\x13crypto_pricing_mode\x18\x0e \x01(\tR\x11cryptoPricingMode\x12*\n" +
	"\x11crypto_price_usdt\x18\x0f \x01(\tR\x0fcryptoPriceUsdt\x120\n" +
	"\x14effective_usdt_price\x18\x10 \x01(\tR\x12effectiveUsdtPrice\x12 \n" +
	"\frub_per_usdt\x18\x11 \x01(\tR\n" +
	"rubPerUsdt\"L\n" +
	"\x10ProductAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"A\n" +
	"\x15ProductAttributeInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x93\x01\n" +
	"\x15ProductCharacteristic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12T\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v24.martketplace.vkr.catalog.v1.domain.ProductAttributeR\n" +
	"attributes\"\x8d\x01\n" +
	"\x1aProductCharacteristicInput\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12Y\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v29.martketplace.vkr.catalog.v1.domain.ProductAttributeInputR\n" +
	"attributes\"I\n" +
	"\fProductImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x17\n" +
	"\ais_main\x18\x03 \x01(\bR\x06isMain\">\n" +
	"\x11ProductImageInput\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x17\n" +
	"\ais_main\x18\x02 \x01(\bR\x06isMainBCZAgithub.com/martketplace-vkr/catalog/pkg/api/grpc/v1/domain;domainb\x06proto3"

var (
	file_v1_domain_catalog_domain_proto_rawDescOnce sync.Once
	file_v1_domain_catalog_domain_proto_rawDescData []byte
)

func file_v1_domain_catalog_domain_proto_rawDescGZIP() []byte {
	file_v1_domain_catalog_domain_proto_rawDescOnce.Do(func() {
		file_v1_domain_catalog_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_domain_catalog_domain_proto_rawDesc), len(file_v1_domain_catalog_domain_proto_rawDesc)))
	})
	return file_v1_domain_catalog_domain_proto_rawDescData
}

var file_v1_domain_catalog_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_domain_catalog_domain_proto_goTypes = []any{
	(*Category)(nil),                   // 0: martketplace.vkr.catalog.v1.domain.Category
	(*Product)(nil),                    // 1: martketplace.vkr.catalog.v1.domain.Product
	(*ProductAttribute)(nil),           // 2: martketplace.vkr.catalog.v1.domain.ProductAttribute
	(*ProductAttributeInput)(nil),      // 3: martketplace.vkr.catalog.v1.domain.ProductAttributeInput
	(*ProductCharacteristic)(nil),      // 4: martketplace.vkr.catalog.v1.domain.ProductCharacteristic
	(*ProductCharacteristicInput)(nil), // 5: martketplace.vkr.catalog.v1.domain.ProductCharacteristicInput
	(*ProductImage)(nil),               // 6: martketplace.vkr.catalog.v1.domain.ProductImage
	(*ProductImageInput)(nil),          // 7: martketplace.vkr.catalog.v1.domain.ProductImageInput
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_v1_domain_catalog_domain_proto_depIdxs = []int32{
	0,  // 0: martketplace.vkr.catalog.v1.domain.Category.children:type_name -> martketplace.vkr.catalog.v1.domain.Category
	8,  // 1: martketplace.vkr.catalog.v1.domain.Category.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: martketplace.vkr.catalog.v1.domain.Category.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: martketplace.vkr.catalog.v1.domain.Product.attributes:type_name -> martketplace.vkr.catalog.v1.domain.ProductAttribute
	6,  // 4: martketplace.vkr.catalog.v1.domain.Product.images:type_name -> martketplace.vkr.catalog.v1.domain.ProductImage
	8,  // 5: martketplace.vkr.catalog.v1.domain.Product.created_at:type_name -> google.protobuf.Timestamp
	8,  // 6: martketplace.vkr.catalog.v1.domain.Product.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 7: martketplace.vkr.catalog.v1.domain.Product.characteristics:type_name -> martketplace.vkr.catalog.v1.domain.ProductCharacteristic
	2,  // 8: martketplace.vkr.catalog.v1.domain.ProductCharacteristic.attributes:type_name -> martketplace.vkr.catalog.v1.domain.ProductAttribute
	3,  // 9: martketplace.vkr.catalog.v1.domain.ProductCharacteristicInput.attributes:type_name -> martketplace.vkr.catalog.v1.domain.ProductAttributeInput
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_domain_catalog_domain_proto_init() }
func file_v1_domain_catalog_domain_proto_init() {
	if File_v1_domain_catalog_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_domain_catalog_domain_proto_rawDesc), len(file_v1_domain_catalog_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_domain_catalog_domain_proto_goTypes,
		DependencyIndexes: file_v1_domain_catalog_domain_proto_depIdxs,
		MessageInfos:      file_v1_domain_catalog_domain_proto_msgTypes,
	}.Build()
	File_v1_domain_catalog_domain_proto = out.File
	file_v1_domain_catalog_domain_proto_goTypes = nil
	file_v1_domain_catalog_domain_proto_depIdxs = nil
}
