// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/cart/catalog_cart_service.proto

package cart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogCartService_GetProductList_FullMethodName = "/martketplace.vkr.catalog.v1.cart.CatalogCartService/GetProductList"
)

// CatalogCartServiceClient is the client API for CatalogCartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogCartServiceClient interface {
	GetProductList(ctx context.Context, in *GetProductListRequest, opts ...grpc.CallOption) (*GetProductListResponse, error)
}

type catalogCartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogCartServiceClient(cc grpc.ClientConnInterface) CatalogCartServiceClient {
	return &catalogCartServiceClient{cc}
}

func (c *catalogCartServiceClient) GetProductList(ctx context.Context, in *GetProductListRequest, opts ...grpc.CallOption) (*GetProductListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductListResponse)
	err := c.cc.Invoke(ctx, CatalogCartService_GetProductList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogCartServiceServer is the server API for CatalogCartService service.
// All implementations must embed UnimplementedCatalogCartServiceServer
// for forward compatibility.
type CatalogCartServiceServer interface {
	GetProductList(context.Context, *GetProductListRequest) (*GetProductListResponse, error)
	mustEmbedUnimplementedCatalogCartServiceServer()
}

// UnimplementedCatalogCartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogCartServiceServer struct{}

func (UnimplementedCatalogCartServiceServer) GetProductList(context.Context, *GetProductListRequest) (*GetProductListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductList not implemented")
}
func (UnimplementedCatalogCartServiceServer) mustEmbedUnimplementedCatalogCartServiceServer() {}
func (UnimplementedCatalogCartServiceServer) testEmbeddedByValue()                            {}

// UnsafeCatalogCartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogCartServiceServer will
// result in compilation errors.
type UnsafeCatalogCartServiceServer interface {
	mustEmbedUnimplementedCatalogCartServiceServer()
}

func RegisterCatalogCartServiceServer(s grpc.ServiceRegistrar, srv CatalogCartServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatalogCartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogCartService_ServiceDesc, srv)
}

func _CatalogCartService_GetProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogCartServiceServer).GetProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogCartService_GetProductList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogCartServiceServer).GetProductList(ctx, req.(*GetProductListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogCartService_ServiceDesc is the grpc.ServiceDesc for CatalogCartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogCartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "martketplace.vkr.catalog.v1.cart.CatalogCartService",
	HandlerType: (*CatalogCartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductList",
			Handler:    _CatalogCartService_GetProductList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/cart/catalog_cart_service.proto",
}
