// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/cart/catalog_cart_service.proto

package cart

import (
	domain "github.com/martketplace-vkr/catalog/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []int64                `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListRequest) Reset() {
	*x = GetProductListRequest{}
	mi := &file_v1_cart_catalog_cart_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListRequest) ProtoMessage() {}

func (x *GetProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cart_catalog_cart_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListRequest.ProtoReflect.Descriptor instead.
func (*GetProductListRequest) Descriptor() ([]byte, []int) {
	return file_v1_cart_catalog_cart_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductListRequest) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type GetProductListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*domain.Product      `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListResponse) Reset() {
	*x = GetProductListResponse{}
	mi := &file_v1_cart_catalog_cart_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListResponse) ProtoMessage() {}

func (x *GetProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cart_catalog_cart_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListResponse.ProtoReflect.Descriptor instead.
func (*GetProductListResponse) Descriptor() ([]byte, []int) {
	return file_v1_cart_catalog_cart_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductListResponse) GetProducts() []*domain.Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_v1_cart_catalog_cart_service_proto protoreflect.FileDescriptor

const file_v1_cart_catalog_cart_service_proto_rawDesc = "" +
	"\n" +
	"\"v1/cart/catalog_cart_service.proto\x12 martketplace.vkr.catalog.v1.cart\x1a\x1ev1/domain/catalog_domain.proto\"8\n" +
	"\x15GetProductListRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\x03R\n" +
	"productIds\"a\n" +
	"\x16GetProductListResponse\x12G\n" +
	"\bproducts\x18\x01 \x03(\v2+.martketplace.vkr.catalog.v1.domain.ProductR\bproducts2\x9a\x01\n" +
	"\x12CatalogCartService\x12\x83\x01\n" +
	"\x0eGetProductList\x127.martketplace.vkr.catalog.v1.cart.GetProductListRequest\x1a8.martketplace.vkr.catalog.v1.cart.GetProductListResponseB?Z=github.com/martketplace-vkr/catalog/pkg/api/grpc/v1/cart;cartb\x06proto3"

var (
	file_v1_cart_catalog_cart_service_proto_rawDescOnce sync.Once
	file_v1_cart_catalog_cart_service_proto_rawDescData []byte
)

func file_v1_cart_catalog_cart_service_proto_rawDescGZIP() []byte {
	file_v1_cart_catalog_cart_service_proto_rawDescOnce.Do(func() {
		file_v1_cart_catalog_cart_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_cart_catalog_cart_service_proto_rawDesc), len(file_v1_cart_catalog_cart_service_proto_rawDesc)))
	})
	return file_v1_cart_catalog_cart_service_proto_rawDescData
}

var file_v1_cart_catalog_cart_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_cart_catalog_cart_service_proto_goTypes = []any{
	(*GetProductListRequest)(nil),  // 0: martketplace.vkr.catalog.v1.cart.GetProductListRequest
	(*GetProductListResponse)(nil), // 1: martketplace.vkr.catalog.v1.cart.GetProductListResponse
	(*domain.Product)(nil),         // 2: martketplace.vkr.catalog.v1.domain.Product
}
var file_v1_cart_catalog_cart_service_proto_depIdxs = []int32{
	2, // 0: martketplace.vkr.catalog.v1.cart.GetProductListResponse.products:type_name -> martketplace.vkr.catalog.v1.domain.Product
	0, // 1: martketplace.vkr.catalog.v1.cart.CatalogCartService.GetProductList:input_type -> martketplace.vkr.catalog.v1.cart.GetProductListRequest
	1, // 2: martketplace.vkr.catalog.v1.cart.CatalogCartService.GetProductList:output_type -> martketplace.vkr.catalog.v1.cart.GetProductListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_cart_catalog_cart_service_proto_init() }
func file_v1_cart_catalog_cart_service_proto_init() {
	if File_v1_cart_catalog_cart_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_cart_catalog_cart_service_proto_rawDesc), len(file_v1_cart_catalog_cart_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_cart_catalog_cart_service_proto_goTypes,
		DependencyIndexes: file_v1_cart_catalog_cart_service_proto_depIdxs,
		MessageInfos:      file_v1_cart_catalog_cart_service_proto_msgTypes,
	}.Build()
	File_v1_cart_catalog_cart_service_proto = out.File
	file_v1_cart_catalog_cart_service_proto_goTypes = nil
	file_v1_cart_catalog_cart_service_proto_depIdxs = nil
}
