// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/client/catalog_client_service.proto

package client

import (
	domain "github.com/martketplace-vkr/catalog/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCategoriesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentId        int64                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	FilterByParent  bool                   `protobuf:"varint,2,opt,name=filter_by_parent,json=filterByParent,proto3" json:"filter_by_parent,omitempty"`
	IncludeChildren bool                   `protobuf:"varint,3,opt,name=include_children,json=includeChildren,proto3" json:"include_children,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_catalog_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCategoriesRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *GetCategoriesRequest) GetFilterByParent() bool {
	if x != nil {
		return x.FilterByParent
	}
	return false
}

func (x *GetCategoriesRequest) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*domain.Category     `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_catalog_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCategoriesResponse) GetCategories() []*domain.Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	VendorId      int64                  `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     uint64                 `protobuf:"varint,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_catalog_client_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListProductsRequest) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetPageToken() uint64 {
	if x != nil {
		return x.PageToken
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*domain.Product      `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken uint64                 `protobuf:"varint,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_catalog_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsResponse) GetProducts() []*domain.Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetNextPageToken() uint64 {
	if x != nil {
		return x.NextPageToken
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_catalog_client_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *domain.Product        `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_catalog_client_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_catalog_client_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductResponse) GetProduct() *domain.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_v1_client_catalog_client_service_proto protoreflect.FileDescriptor

const file_v1_client_catalog_client_service_proto_rawDesc = "" +
	"\n" +
	"&v1/client/catalog_client_service.proto\x12\"martketplace.vkr.catalog.v1.client\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ev1/domain/catalog_domain.proto\"\x88\x01\n" +
	"\x14GetCategoriesRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x03R\bparentId\x12(\n" +
	"\x10filter_by_parent\x18\x02 \x01(\bR\x0efilterByParent\x12)\n" +
	"\x10include_children\x18\x03 \x01(\bR\x0fincludeChildren\"e\n" +
	"\x15GetCategoriesResponse\x12L\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2,.martketplace.vkr.catalog.v1.domain.CategoryR\n" +
	"categories\"\x8f\x01\n" +
	"\x13ListProductsRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\x04R\tpageToken\"\x87\x01\n" +
	"\x14ListProductsResponse\x12G\n" +
	"\bproducts\x18\x01 \x03(\v2+.martketplace.vkr.catalog.v1.domain.ProductR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\x04R\rnextPageToken\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"[\n" +
	"\x12GetProductResponse\x12E\n" +
	"\aproduct\x18\x01 \x01(\v2+.martketplace.vkr.catalog.v1.domain.ProductR\aproduct2\x9e\x03\n" +
	"\x14CatalogClientService\x12\x84\x01\n" +
	"\rGetCategories\x128.martketplace.vkr.catalog.v1.client.GetCategoriesRequest\x1a9.martketplace.vkr.catalog.v1.client.GetCategoriesResponse\x12\x81\x01\n" +
	"\fListProducts\x127.martketplace.vkr.catalog.v1.client.ListProductsRequest\x1a8.martketplace.vkr.catalog.v1.client.ListProductsResponse\x12{\n" +
	"\n" +
	"GetProduct\x125.martketplace.vkr.catalog.v1.client.GetProductRequest\x1a6.martketplace.vkr.catalog.v1.client.GetProductResponseBCZAgithub.com/martketplace-vkr/catalog/pkg/api/grpc/v1/client;clientb\x06proto3"

var (
	file_v1_client_catalog_client_service_proto_rawDescOnce sync.Once
	file_v1_client_catalog_client_service_proto_rawDescData []byte
)

func file_v1_client_catalog_client_service_proto_rawDescGZIP() []byte {
	file_v1_client_catalog_client_service_proto_rawDescOnce.Do(func() {
		file_v1_client_catalog_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_client_catalog_client_service_proto_rawDesc), len(file_v1_client_catalog_client_service_proto_rawDesc)))
	})
	return file_v1_client_catalog_client_service_proto_rawDescData
}

var file_v1_client_catalog_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_client_catalog_client_service_proto_goTypes = []any{
	(*GetCategoriesRequest)(nil),  // 0: martketplace.vkr.catalog.v1.client.GetCategoriesRequest
	(*GetCategoriesResponse)(nil), // 1: martketplace.vkr.catalog.v1.client.GetCategoriesResponse
	(*ListProductsRequest)(nil),   // 2: martketplace.vkr.catalog.v1.client.ListProductsRequest
	(*ListProductsResponse)(nil),  // 3: martketplace.vkr.catalog.v1.client.ListProductsResponse
	(*GetProductRequest)(nil),     // 4: martketplace.vkr.catalog.v1.client.GetProductRequest
	(*GetProductResponse)(nil),    // 5: martketplace.vkr.catalog.v1.client.GetProductResponse
	(*domain.Category)(nil),       // 6: martketplace.vkr.catalog.v1.domain.Category
	(*domain.Product)(nil),        // 7: martketplace.vkr.catalog.v1.domain.Product
}
var file_v1_client_catalog_client_service_proto_depIdxs = []int32{
	6, // 0: martketplace.vkr.catalog.v1.client.GetCategoriesResponse.categories:type_name -> martketplace.vkr.catalog.v1.domain.Category
	7, // 1: martketplace.vkr.catalog.v1.client.ListProductsResponse.products:type_name -> martketplace.vkr.catalog.v1.domain.Product
	7, // 2: martketplace.vkr.catalog.v1.client.GetProductResponse.product:type_name -> martketplace.vkr.catalog.v1.domain.Product
	0, // 3: martketplace.vkr.catalog.v1.client.CatalogClientService.GetCategories:input_type -> martketplace.vkr.catalog.v1.client.GetCategoriesRequest
	2, // 4: martketplace.vkr.catalog.v1.client.CatalogClientService.ListProducts:input_type -> martketplace.vkr.catalog.v1.client.ListProductsRequest
	4, // 5: martketplace.vkr.catalog.v1.client.CatalogClientService.GetProduct:input_type -> martketplace.vkr.catalog.v1.client.GetProductRequest
	1, // 6: martketplace.vkr.catalog.v1.client.CatalogClientService.GetCategories:output_type -> martketplace.vkr.catalog.v1.client.GetCategoriesResponse
	3, // 7: martketplace.vkr.catalog.v1.client.CatalogClientService.ListProducts:output_type -> martketplace.vkr.catalog.v1.client.ListProductsResponse
	5, // 8: martketplace.vkr.catalog.v1.client.CatalogClientService.GetProduct:output_type -> martketplace.vkr.catalog.v1.client.GetProductResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_client_catalog_client_service_proto_init() }
func file_v1_client_catalog_client_service_proto_init() {
	if File_v1_client_catalog_client_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_client_catalog_client_service_proto_rawDesc), len(file_v1_client_catalog_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_client_catalog_client_service_proto_goTypes,
		DependencyIndexes: file_v1_client_catalog_client_service_proto_depIdxs,
		MessageInfos:      file_v1_client_catalog_client_service_proto_msgTypes,
	}.Build()
	File_v1_client_catalog_client_service_proto = out.File
	file_v1_client_catalog_client_service_proto_goTypes = nil
	file_v1_client_catalog_client_service_proto_depIdxs = nil
}
